// flow-typed signature: c432b89d8b8611984f7ed813faf6a29d
// flow-typed version: <<STUB>>/standard-loader_v^6.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'standard-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'standard-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'standard-loader/index' {
  declare module.exports: $Exports<'standard-loader'>;
}
declare module 'standard-loader/index.js' {
  declare module.exports: $Exports<'standard-loader'>;
}
